begin;
drop function if exists create_expense(uuid,uuid,text,jsonb,numeric,timestamptz,numeric,text);
drop function if exists update_expense(uuid,uuid,text,jsonb,numeric,timestamptz,numeric,text);
drop function if exists delete_expense(uuid);
drop function if exists create_deposit(uuid,numeric,numeric,timestamptz);
drop function if exists delete_deposit(uuid);
drop function if exists create_transfer(uuid,uuid,numeric,text,timestamptz);
drop function if exists delete_transfer(uuid);
drop function if exists create_exchange(uuid,uuid,numeric,numeric,timestamptz);
drop function if exists delete_exchange(uuid);
drop function if exists create_card(uuid,text,text);
drop function if exists create_card_spend(uuid,numeric,text,numeric,timestamptz);
drop function if exists delete_card_spend(uuid);
drop function if exists period_start(text);
drop function if exists period_spend(uuid,uuid,uuid,timestamptz,timestamptz);
drop function if exists _write_legs(uuid,uuid,jsonb,timestamptz);
drop function if exists _net_usd(jsonb,numeric);
drop function if exists _check_rate(uuid,numeric,boolean);
drop function if exists _member_acct(uuid,text);
drop function if exists _lock_accounts(uuid[]);
drop function if exists _is_admin(members);
drop function if exists _caller(uuid);
commit;
